describe("renderer.init", function()
  it("exposes overlay, mirror, and statusline adapters", function()
    local renderer = require("ghost-reader.renderer")
    assert.is_table(renderer.overlay)
    assert.is_table(renderer.mirror)
    assert.is_table(renderer.statusline)
    assert.is_function(renderer.create)
  end)

  it("raises the exact unknown renderer error", function()
    local renderer = require("ghost-reader.renderer")
    assert.has_error(function()
      renderer.get("bogus")
    end, "unknown reader view: bogus")
  end)
end)
