local bookmark = require("ghost-reader.reader.bookmark")

describe("bookmark", function()
  it("adds and retrieves bookmarks", function()
    local bm = bookmark.new("test_book")
    bm:add(5, "important passage")
    assert.equal(1, #bm:list())
    assert.equal("important passage", bm:list()[1].note)
  end)

  it("removes bookmark by line", function()
    local bm = bookmark.new("test_book")
    bm:add(5, "note")
    bm:remove(5)
    assert.equal(0, #bm:list())
  end)

  it("persists to file", function()
    local tmp = os.tmpname()
    local bm = bookmark.new("test_book", tmp)
    bm:add(10, "test note")
    bm:save()

    local bm2 = bookmark.new("test_book", tmp)
    bm2:load()
    assert.equal(1, #bm2:list())
    os.remove(tmp)
  end)
end)
