describe("renderer.init", function()
  it("exposes overlay, mirror, and statusline adapters", function()
    local renderer = require("ghost-reader.renderer")
    assert.is_table(renderer.overlay)
    assert.is_table(renderer.mirror)
    assert.is_table(renderer.statusline)
    assert.is_function(renderer.create)
  end)
end)
