local config = require("ghost-reader.config")

describe("config", function()
  it("returns the new defaults", function()
    local cfg = config.setup()
    assert.equal("overlay", cfg.reader.renderer)
    assert.equal(3, cfg.reader.visible_blocks)
    assert.equal("j", cfg.keymaps.controls.next_content)
    assert.equal("gh", cfg.keymaps.controls.hide)
    assert.equal("<Esc>", cfg.keymaps.controls.exit_controls)
    assert.is_truthy(cfg.paths.cache_dir:match("ghost%-reader/$"))
    assert.is_nil(cfg.cache_dir)
    assert.is_nil(cfg.data_dir)
  end)

  it("rejects legacy keys", function()
    assert.has_error(function() config.setup({ boss_key = {} }) end, "unknown config key: boss_key")
    assert.has_error(function() config.setup({ statusline = { mode = "manual" } }) end,
      "unknown config key: statusline.mode")
  end)

  it("accepts false to disable a mapping", function()
    local cfg = config.setup({ keymaps = { controls = { help = false } } })
    assert.is_false(cfg.keymaps.controls.help)
  end)

  it("rejects invalid values", function()
    assert.has_error(function() config.setup({ reader = { visible_blocks = 0 } }) end)
    assert.has_error(function() config.setup({ statusline = { interval = "fast" } }) end)
    assert.has_error(function() config.setup({ paths = { cache_dir = 42 } }) end)
  end)

  it("rejects malformed section values", function()
    assert.has_error(function() config.setup({ reader = false }) end, "invalid config value at reader: expected table")
    assert.has_error(function() config.setup({ statusline = "fast" }) end, "invalid config value at statusline: expected table")
    assert.has_error(function() config.setup({ stealth = false }) end, "invalid config value at stealth: expected table")
    assert.has_error(function() config.setup({ paths = false }) end, "invalid config value at paths: expected table")
    assert.has_error(function() config.setup({ keymaps = false }) end, "invalid config value at keymaps: expected table")
  end)
end)
